version: "3.8"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    image: 'postgres:14-alpine'
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=food_menu
    ports:
      - '54320:5432'


